version: "3.8"

networks:
  plaid-quickstart:
    name: plaid-quickstart
services:
  plaid-server:
    networks:
      - plaid-quickstart
    build:
      dockerfile: ./node/Dockerfile
    ports: ["8000:8000"]
    env_file:
      - .env
  plaid-frontend:
    environment:
      REACT_APP_API_HOST: http://plaid-server:8000
    networks:
      - plaid-quickstart
    depends_on:
      - plaid-server
    build:
      dockerfile: ./frontend/Dockerfile
    ports: ["3000:3000"]
